# Generated by Django 4.2.5 on 2023-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=256, unique=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Загруженный файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки файла')),
                ('processed', models.BooleanField(default=False, verbose_name='Файл обработан')),
            ],
        ),
    ]
